apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: todo-api
spec:
  type: NodePort
  ports:
    - port: 28002
      targetPort: 28002
      nodePort: 30002
  selector:
    app: todo-api-pod
    type: backend
